version: 1.0.{build}
image: Visual Studio 2022
before_build:
- cmd: nuget restore 
build:
  project: P2PConnect.sln
  verbosity: minimal
before_package:
- ps: >-
    dotnet publish -r linux-x64 -c Release -o "C:\projects\P2PConnect\P2PConnectRelease"
artifacts:
- path: P2PConnectRelease
  name: P2PConnectRelease
deploy:
- provider: Environment
  name: Production
  on:
    branch: Master